name: Check module maintainers' approvals
on:
  pull_request_review:
    types: [submitted]

jobs:
  check_review:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Run BCR PR Review Approver
        uses: meteorcloudy/continuous-integration/actions/bcr-pr-review-approver@bcr_testing
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{github.event.pull_request.number}}
          body: "Hallo, world."