name: Check module maintainers' approvals
on:
  pull_request_target:
    branches:
      - main
    paths:
      - 'modules/**'

  pull_request_review:
    types: [submitted]

jobs:
  check_review:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Run BCR PR Review Approver
        # if: ${{ github.event.review.user.login != 'meteorcloudy' }}
        uses: meteorcloudy/continuous-integration/actions/bcr-pr-review-approver@bcr_testing
        with:
          # This token needs to be updated annually on Feb 05.
          token: ${{ secrets.BCR_PR_REVIEW_HELPER_TOKEN }}
